# Simple workflow for deploying a React app (Vite) to GitHub Pages

name: Deploy React App to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      # 4. Setup Pages (REMOVIDAS AS LINHAS DE CONFIGURAÇÃO QUE CAUSAVAM O ERRO)
      - name: Setup Pages
        uses: actions/configure-pages@v5
          
      # 5. Upload the compiled artifact (Onde definimos a pasta 'dist')
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Usamos 'dist' (a saída do Vite)
          path: './dist' 
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4